<?php

/**
 * BaseIndustry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $FacebookPage
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getFacebookPage() Returns the current record's "FacebookPage" collection
 * @method Industry            setName()         Sets the current record's "name" value
 * @method Industry            setFacebookPage() Sets the current record's "FacebookPage" collection
 * 
 * @package    insights
 * @subpackage model
 * @author     Loopster Media
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIndustry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('industry');
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FacebookPage', array(
             'local' => 'id',
             'foreign' => 'industry_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}