<?php

/**
 * BaseFanCount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $facebook_page_id
 * @property integer $fancount
 * @property datetime $date
 * @property FacebookPage $FacebookPage
 * @property Doctrine_Collection $FanCounts
 * 
 * @method integer             getFacebookPageId()   Returns the current record's "facebook_page_id" value
 * @method integer             getFancount()         Returns the current record's "fancount" value
 * @method datetime            getDate()             Returns the current record's "date" value
 * @method FacebookPage        getFacebookPage()     Returns the current record's "FacebookPage" value
 * @method Doctrine_Collection getFanCounts()        Returns the current record's "FanCounts" collection
 * @method FanCount            setFacebookPageId()   Sets the current record's "facebook_page_id" value
 * @method FanCount            setFancount()         Sets the current record's "fancount" value
 * @method FanCount            setDate()             Sets the current record's "date" value
 * @method FanCount            setFacebookPage()     Sets the current record's "FacebookPage" value
 * @method FanCount            setFanCounts()        Sets the current record's "FanCounts" collection
 * 
 * @package    insights
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFanCount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fan_count');
        $this->hasColumn('facebook_page_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fancount', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FacebookPage', array(
             'local' => 'facebook_page_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Message as FanCounts', array(
             'local' => 'id',
             'foreign' => 'fan_count_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}