<?php

/**
 * BaseInclusionRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $facebook_url
 * @property sfGuardUser $User
 * 
 * @method integer          getUserId()       Returns the current record's "user_id" value
 * @method string           getFacebookUrl()  Returns the current record's "facebook_url" value
 * @method sfGuardUser      getUser()         Returns the current record's "User" value
 * @method InclusionRequest setUserId()       Sets the current record's "user_id" value
 * @method InclusionRequest setFacebookUrl()  Sets the current record's "facebook_url" value
 * @method InclusionRequest setUser()         Sets the current record's "User" value
 * 
 * @package    insights
 * @subpackage model
 * @author     Loopster Media
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInclusionRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inclusion_request');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('facebook_url', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}