<?php

/**
 * BaseIndustry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property FacebookPage $FacebookPage
 * 
 * @method string       getName()         Returns the current record's "name" value
 * @method FacebookPage getFacebookPage() Returns the current record's "FacebookPage" value
 * @method Industry     setName()         Sets the current record's "name" value
 * @method Industry     setFacebookPage() Sets the current record's "FacebookPage" value
 * 
 * @package    insights
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIndustry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('industry');
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FacebookPage', array(
             'local' => 'id',
             'foreign' => 'industry_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}