<?php

/**
 * BaseFacebookPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $notes
 * @property integer $industry_id
 * @property Doctrine_Collection $Industry
 * @property Doctrine_Collection $FanCounts
 * @property Doctrine_Collection $FacebookPages
 * 
 * @method string              getUrl()           Returns the current record's "url" value
 * @method string              getNotes()         Returns the current record's "notes" value
 * @method integer             getIndustryId()    Returns the current record's "industry_id" value
 * @method Doctrine_Collection getIndustry()      Returns the current record's "Industry" collection
 * @method Doctrine_Collection getFanCounts()     Returns the current record's "FanCounts" collection
 * @method Doctrine_Collection getFacebookPages() Returns the current record's "FacebookPages" collection
 * @method FacebookPage        setUrl()           Sets the current record's "url" value
 * @method FacebookPage        setNotes()         Sets the current record's "notes" value
 * @method FacebookPage        setIndustryId()    Sets the current record's "industry_id" value
 * @method FacebookPage        setIndustry()      Sets the current record's "Industry" collection
 * @method FacebookPage        setFanCounts()     Sets the current record's "FanCounts" collection
 * @method FacebookPage        setFacebookPages() Sets the current record's "FacebookPages" collection
 * 
 * @package    insights
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacebookPage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('facebook_page');
        $this->hasColumn('url', 'string', 511, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 511,
             ));
        $this->hasColumn('notes', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('industry_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Industry', array(
             'local' => 'industry_id',
             'foreign' => 'id',
             'onDelete' => 'NO ACTION'));

        $this->hasMany('FanCount as FanCounts', array(
             'local' => 'id',
             'foreign' => 'facebook_page_id'));

        $this->hasMany('Message as FacebookPages', array(
             'local' => 'id',
             'foreign' => 'facebook_page_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}