<?php

/**
 * BaseTokens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * 
 * @method string getToken() Returns the current record's "token" value
 * @method Tokens setToken() Sets the current record's "token" value
 * 
 * @package    insights
 * @subpackage model
 * @author     Loopster Media
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTokens extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tokens');
        $this->hasColumn('token', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}