<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/08 13:40:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=lminsights',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
