<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/07/08 13:40:38
$this->security = array (
  'sfguarduser' => 
  array (
    'is_secure' => false,
  ),
  'sfguardregister' => 
  array (
    'is_secure' => false,
  ),
  'sfguardforgotpassword' => 
  array (
    'is_secure' => false,
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
