<?php

/**
 * FacebookPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    insights
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FacebookPage extends BaseFacebookPage
{
    /**
     *
     * @return String Returns the username of the Facebook page. eg: http://www.facebook.com/<username> 
     */
    public function getName() {
        $url = $this->getUrl();
        // break up the URL and get the parts we want from it
        $endIndex = strpos($url,"?"); // remove QS params
        if ($endIndex > 0)
            $url = substr ($url, 0, $endIndex);
        // drop anything after the last '/'
        $endIndex = strrpos($url, "/");
        $url = substr($url, $endIndex + 1, strlen($url) - $endIndex - 1);
        return $url;
    }

    /**
     * Return the latest fancount value for this Facebook Page
     *
     * @return object
     */
    public function getFancount() {
        $q = FanCountTable::getInstance()->createQuery()
                ->select("MAX(date), fancount as fancount")
                ->where("facebook_page_id = ?",$this->getId())
                ->execute();
        return $q[0]->getFancount();
    }

}
