<?php

/**
 * InclusionRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InclusionRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InclusionRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InclusionRequest');
    }
}