<?php

/**
 * IndustryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndustryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndustryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Industry');
    }

    /**
     *
     * @return object IndustryTable
     */
    public static function getIndustries() {
        return Doctrine_Core::getTable("Industry")->findAll();

    }

    /**
     *
     * @return array
     */
    public static function getIndustrySelectOptions() {
        $industries = self::getIndustries();
        $arr = array();
        foreach($industries as $val) {
            $arr[$val->getName()] = $val->getName();
        }
        return $arr;
    }
}