<?php

/**
 * TokensTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TokensTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TokensTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tokens');
    }

    /**
     * Returns the latest token using the 'created_at' field
     *
     * @return string 
     */
    public function getLatestToken() {

        $connection = Doctrine_Manager::connection();
        $query = "SELECT MAX(created_at) AS max, token FROM tokens";
        $statement = $connection->execute($query);
        $statement->execute();
        $resultset = $statement->fetch(PDO::FETCH_ASSOC);

        if (isset($resultset["token"]) && $resultset["token"] != "")
            return $resultset["token"];
        return "";
    }
}