<?php
// auto-generated by sfViewConfigHandler
// date: 2011/07/08 13:40:45
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/base/jquery-ui.css', '', array ());
  $response->addStylesheet('tipsy.css', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js', '', array ());
  $response->addJavascript('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js', '', array ());
  $response->addJavascript('jquery.flot.js', '', array ());
  $response->addJavascript('jquery.tipsy.js', '', array ());
  $response->addJavascript('lminsights.js', '', array ());


